version: "3.9"
services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - CLAUDE_API_KEY=${CLAUDE_API_KEY}
      - BOLT_API_KEY=${BOLT_API_KEY}
      - MANUS_API_KEY=${MANUS_API_KEY}
