version: "3.3"

services:
  backend:
    build:
      context: ./backend
    container_name: backend
    ports:
      - "8010:8000"  # Porta do host -> porta interna do container (FastAPI)
    depends_on:
      - super__postgres
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - DATABASE_URL=postgresql+psycopg2://postgres:postgres@super__postgres:5432/super__postgres

  superagi:
    build:
      context: ./superagi
    container_name: superagi
    ports:
      - "3001:3000"  # Porta do host -> porta interna do SuperAGI
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ENCRYPTION_KEY=${ENCRYPTION_KEY}
    env_file:
      - ./superagi/.env     
    depends_on:
      - super__postgres

  super__postgres:
    image: postgres:14
    container_name: super__postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: super__postgres
    volumes:
      - superagi_pgdata:/var/lib/postgresql/data
    ports:
      - "5433:5432"  # Porta do host -> PostgreSQL

volumes:
  superagi_pgdata:

