version: "3.3"

services:
  backend:
    build:
      context: ./backend
    container_name: backend
    ports:
      - "8010:8000"  # Host -> Backend
    depends_on:
      - superagi
      - super__postgres
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - CLAUDE_API_KEY=${CLAUDE_API_KEY}
      - SERPAPI_API_KEY=${SERPAPI_API_KEY}
      - DATABASE_URL=postgresql+psycopg2://postgres:postgres@super__postgres:5432/super__postgres
      - SUPERAGI_URL=${SUPERAGI_URL}
      - SUPERAGI_LEARN_URL=${SUPERAGI_LEARN_URL}
    env_file:
      - .env

  superagi:
    build:
      context: ./superagi
    container_name: superagi
    ports:
      - "3001:3000"  # Host -> SuperAGI
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ENCRYPTION_KEY=${ENCRYPTION_KEY}
      - DATABASE_URL=postgresql+psycopg2://postgres:postgres@super__postgres:5432/super__postgres
    env_file:
      - ./superagi/.env
    volumes:
      - ./superagi/config.yaml:/app/config.yaml
    depends_on:
      - super__postgres

  super__postgres:
    image: postgres:14
    container_name: super__postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: super__postgres
    volumes:
      - superagi_pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"  # ← alterado para padrão local

volumes:
  superagi_pgdata:

